/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unit_tests.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "our_math.h"

START_TEST(test_abs) {
  ck_assert_int_eq(abs(-7), our_abs(-7));
  ck_assert_int_eq(abs(-98), our_abs(-98));
  ck_assert_int_eq(abs(123), our_abs(123));
  ck_assert_int_eq(abs(10009), our_abs(10009));
  ck_assert_int_eq(abs(-10009), our_abs(-10009));
  ck_assert_int_eq(abs(0), our_abs(0));
  ck_assert_int_eq(abs(1), our_abs(1));
}
END_TEST

START_TEST(test_acos1) {
  for (float k = -1; k <= 1; k += 0.1) {
    double a = acos(k);
    double b = our_acos(k);
    ck_assert_double_eq_tol(a, b, 1e-7);
  }
}
END_TEST

START_TEST(test_acos2) {
  for (float k = -1; k <= 1; k += 0.0305) {
    double a = acos(k);
    double b = our_acos(k);
    ck_assert_double_eq_tol(a, b, 1e-7);
  }
}
END_TEST

START_TEST(test_acos3) {
  ck_assert_float_eq(acos(1.0), our_acos(1.0));
  ck_assert_float_eq(acos(-1.0), our_acos(-1.0));
  ck_assert_float_eq(acos(0.0), our_acos(0.0));
  ck_assert_float_eq(acos(-0.0), our_acos(-0.0));
  ck_assert_float_eq(acos(-1 / 2), our_acos(-1 / 2));
  ck_assert_float_eq(acos(1 / 2), our_acos(1 / 2));
  ck_assert_float_ne(acos(3), our_acos(3));
  ck_assert_float_ne(acos(-3), our_acos(-3));
}
END_TEST

START_TEST(test_asin1) {
  ck_assert_float_eq(asin(1.0), our_asin(1.0));
  ck_assert_ldouble_nan(our_asin(our_NAN));
  ck_assert_float_eq(asin(-1.0), our_asin(-1.0));
  ck_assert_float_eq(asin(0.0), our_asin(0.0));
  ck_assert_float_eq(asin(-0.0), our_asin(-0.0));
  ck_assert_float_eq(asin(1 / 2), our_asin(1 / 2));
  ck_assert_float_eq(asin(-1 / 2), our_asin(-1 / 2));
  ck_assert_float_ne(asin(3), our_asin(3));
  ck_assert_float_ne(asin(-3), our_asin(-3));
  ck_assert_ldouble_eq_tol(asin(0.5), our_asin(0.5), 1e-8);
  ck_assert_ldouble_eq_tol(asin(-0.5), our_asin(-0.5), 1e-8);
  ck_assert_ldouble_eq_tol(asin(-1), our_asin(-1), 1e-15);
  ck_assert_ldouble_eq_tol(asin(1), our_asin(1), 1e-15);
  ck_assert_ldouble_eq_tol(asin(0), our_asin(0), 1e-15);
  ck_assert_ldouble_eq_tol(asin(-0), our_asin(-0), 1e-15);
}
END_TEST

START_TEST(test_asin2) {
  for (float k = -1; k <= 1; k += 0.1) {
    double a = asin(k);
    double b = our_asin(k);
    ck_assert_double_eq_tol(a, b, 1e-7);
  }
}
END_TEST

START_TEST(test_asin3) {
  for (float k = -1; k <= 1; k += 0.0771) {
    double a = asin(k);
    double b = our_asin(k);
    ck_assert_double_eq_tol(a, b, 1e-7);
  }
}
END_TEST

START_TEST(test_atan1) {
  ck_assert_float_eq(atan(1.0), our_atan(1.0));
  ck_assert_ldouble_nan(our_atan(our_NAN));
  ck_assert_float_eq(atan(1.1), our_atan(1.1));
  ck_assert_float_eq(atan(-1.0), our_atan(-1.0));
  ck_assert_float_eq(atan(-1.1), our_atan(-1.1));
  ck_assert_float_eq(atan(0.0), our_atan(0.0));
  ck_assert_float_eq(atan(-0.0), our_atan(-0.0));
  ck_assert_float_eq(atan(-1 / 2), our_atan(-1 / 2));
  ck_assert_float_eq(atan(1 / 2), our_atan(1 / 2));
  ck_assert_float_eq(atan(3), our_atan(3));
  ck_assert_float_eq(atan(-3), our_atan(-3));
  ck_assert_ldouble_eq_tol(atan(0.5), our_atan(0.5), 1e-8);
  ck_assert_ldouble_eq_tol(atan(-0.5), our_atan(-0.5), 1e-8);
  ck_assert_ldouble_eq_tol(atan(-1), our_atan(-1), 1e-8);
  ck_assert_ldouble_eq_tol(atan(1), our_atan(1), 1e-8);
  ck_assert_ldouble_eq_tol(atan(1.1), our_atan(1.1), 1e-8);
  ck_assert_ldouble_eq_tol(atan(-2.1), our_atan(-2.1), 1e-8);
  ck_assert_ldouble_eq_tol(atan(0), our_atan(0), 1e-15);
  ck_assert_ldouble_eq_tol(atan(-0), our_atan(-0), 1e-15);
  ck_assert_ldouble_eq_tol(atan(5.123456789123), our_atan(5.123456789123),
                           1e-14);
  ck_assert_ldouble_eq_tol(atan(0.00000004564897), our_atan(0.00000004564897),
                           1e-14);
}
END_TEST

START_TEST(test_atan2) {
  for (float k = -10; k <= 10; k += 4) {
    double a = atan(k);
    double b = our_atan(k);
    ck_assert_double_eq_tol(a, b, 1e-7);
  }
}
END_TEST

START_TEST(test_ceil) {
  ck_assert_double_eq(ceil(INFINITY), our_ceil(our_P_INF));
  ck_assert_double_eq(ceil(-INFINITY), our_ceil(our_N_INF));
  ck_assert_double_nan(ceil(NAN));
  ck_assert_double_nan(our_ceil(our_NAN));
  ck_assert_double_eq(ceil(-7.0), our_ceil(-7.0));
  ck_assert_double_eq(ceil(-98.1), our_ceil(-98.1));
  ck_assert_double_eq(ceil(123.02), our_ceil(123.02));
  ck_assert_double_eq(ceil(10009.00123), our_ceil(10009.00123));
  ck_assert_double_eq(ceil(-10009.555), our_ceil(-10009.555));
  ck_assert_double_eq(ceil(-0.10009), our_ceil(-0.10009));
  ck_assert_double_eq(ceil(-1e-23), our_ceil(-1e-23));
  ck_assert_ldouble_eq(our_ceil(-876554310.23455), ceil(-876554310.23455));
  ck_assert_ldouble_eq(our_ceil(876554310.23455), ceil(876554310.23455));
  ck_assert_ldouble_eq(our_ceil(-0.45), ceil(-0.45));
  ck_assert_ldouble_eq(our_ceil(0.45), ceil(0.45));
  ck_assert_ldouble_eq(our_ceil(-0.00000000000000045),
                       ceil(-0.00000000000000045));
}
END_TEST

START_TEST(test_cos) {
  ck_assert_ldouble_eq_tol(cos(0.5), our_cos(0.5), 1e-15);
  ck_assert_ldouble_eq_tol(cos(-0.5), our_cos(-0.5), 1e-15);
  ck_assert_ldouble_eq_tol(cos(-1), our_cos(-1), 1e-15);
  ck_assert_ldouble_eq_tol(cos(1), our_cos(1), 1e-15);
  ck_assert_ldouble_nan(our_cos(our_N_INF));
  ck_assert_ldouble_nan(our_cos(our_P_INF));
  ck_assert_ldouble_nan(our_cos(our_NAN));
  ck_assert_ldouble_eq_tol(cos(1.1), our_cos(1.1), 1e-15);
  ck_assert_ldouble_eq_tol(cos(-2.1), our_cos(-2.1), 1e-15);
  ck_assert_ldouble_eq_tol(cos(0), our_cos(0), 1e-15);
  ck_assert_ldouble_eq_tol(cos(0), our_cos(0), 1e-15);
  ck_assert_ldouble_eq_tol(cos(-0), our_cos(-0), 1e-15);
  ck_assert_ldouble_eq_tol(cos(5.123456789123), our_cos(5.123456789123), 1e-15);
  ck_assert_ldouble_eq_tol(cos(0.00000004564897), our_cos(0.00000004564897),
                           1e-15);
}
END_TEST

START_TEST(test_exp1) {
  for (double k = -21; k < 21; k += 1) {
    double a = exp(k);
    double b = our_exp(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_exp2) {
  for (double k = -15; k < 15; k += 0.123) {
    double a = exp(k);
    double b = our_exp(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_exp3) {
  for (double k = -5; k < 5; k += 0.00573) {
    double a = exp(k);
    double b = our_exp(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_exp4) {
  ck_assert_ldouble_eq_tol(exp(0.5), our_exp(0.5), 1e-15);
  ck_assert_ldouble_eq_tol(exp(-0.5), our_exp(-0.5), 1e-15);
  ck_assert_ldouble_eq_tol(exp(-1), our_exp(-1), 1e-15);
  ck_assert_ldouble_eq_tol(exp(1), our_exp(1), 1e-15);
  ck_assert_ldouble_eq_tol(exp(1.1), our_exp(1.1), 1e-15);
  ck_assert_ldouble_eq_tol(exp(-2.1), our_exp(-2.1), 1e-15);
  ck_assert_ldouble_eq_tol(exp(0), our_exp(0), 1e-15);
  ck_assert_ldouble_eq_tol(exp(-0), our_exp(-0), 1e-15);
  ck_assert_ldouble_eq_tol(exp(5.123456789123), our_exp(5.123456789123), 1e-8);
  ck_assert_ldouble_eq_tol(exp(0.00000004564897), our_exp(0.00000004564897),
                           1e-15);
  ck_assert_ldouble_eq_tol(exp(20.1), our_exp(20.1), 1e-8);
  ck_assert_ldouble_eq_tol(exp(-20.1), our_exp(-20.1), 1e-8);
}
END_TEST

START_TEST(test_fabs) {
  ck_assert_double_eq(fabs(INFINITY), our_fabs(our_P_INF));
  ck_assert_double_eq(fabs(-INFINITY), our_fabs(our_P_INF));
  ck_assert_double_nan(fabs(NAN));
  ck_assert_double_nan(our_fabs(our_NAN));
  ck_assert_double_eq(fabs(-7.0), our_fabs(-7.0));
  ck_assert_double_eq(fabs(-98.1), our_fabs(-98.1));
  ck_assert_double_eq(fabs(123.02), our_fabs(123.02));
  ck_assert_double_eq(fabs(10009.0), our_fabs(10009.0));
  ck_assert_double_eq(fabs(-10009.555), our_fabs(-10009.555));
  ck_assert_double_eq(fabs(-0.10009), our_fabs(-0.10009));
  ck_assert_double_eq(fabs(-1e23), our_fabs(-1e23));
  ck_assert_ldouble_eq_tol(our_fabs(0.5), fabs(0.5), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-0.5), fabs(-0.5), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-1.0), fabs(-1.0), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(1.0), fabs(1.0), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(1.1), fabs(1.1), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-2.1), fabs(-2.1), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(0.0), fabs(0.0), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-0.0), fabs(-0.0), 1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(5.123456789123), fabs(5.123456789123),
                           1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(0.00000004564897), fabs(0.00000004564897),
                           1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(170000000000000.1), fabs(170000000000000.1),
                           1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-5.123456789123), fabs(-5.123456789123),
                           1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-0.00000004564897), fabs(-0.00000004564897),
                           1e-15);
  ck_assert_ldouble_eq_tol(our_fabs(-170000000000000.1),
                           fabs(-170000000000000.1), 1e-15);
}
END_TEST

START_TEST(test_floor) {
  ck_assert_double_eq(floor(INFINITY), our_floor(our_P_INF));
  ck_assert_double_eq(floor(-INFINITY), our_floor(our_N_INF));
  ck_assert_double_nan(floor(NAN));
  ck_assert_double_nan(our_floor(our_NAN));
  ck_assert_double_eq(floor(-7.0), our_floor(-7.0));
  ck_assert_double_eq(floor(-98.1), our_floor(-98.1));
  ck_assert_double_eq(floor(123.02), our_floor(123.02));
  ck_assert_double_eq(floor(10009.00123), our_floor(10009.00123));
  ck_assert_double_eq(floor(-10009.555), our_floor(-10009.555));
  ck_assert_double_eq(floor(-0.10009), our_floor(-0.10009));
  ck_assert_double_eq(floor(-1e-23), our_floor(-1e-23));
  ck_assert_double_eq(floor(100091234.5), our_floor(100091234.5));
}
END_TEST

START_TEST(test_fmod1) {
  ck_assert_double_nan(fmod(1, 0));
  ck_assert_double_nan(our_fmod(1, 0));
  ck_assert_double_eq(fmod(0, -1), our_fmod(0, -1));
  ck_assert_double_eq(fmod(0, 1), our_fmod(0, 1));
  ck_assert_double_nan(fmod(INFINITY, -1));
  ck_assert_double_nan(our_fmod(INFINITY, -1));
  ck_assert_double_eq(fmod(-1, -INFINITY), our_fmod(-1, our_N_INF));
  ck_assert_double_eq(fmod(0, INFINITY), our_fmod(0, our_P_INF));
  ck_assert_double_nan(our_fmod(0, our_NAN));
  ck_assert_double_nan(fmod(0, NAN));
  ck_assert_double_nan(our_fmod(our_NAN, our_NAN));
  ck_assert_double_nan(fmod(NAN, NAN));
  ck_assert_double_nan(our_fmod(our_NAN, our_P_INF));
  ck_assert_double_nan(our_fmod(our_P_INF, our_NAN));
  ck_assert_double_nan(our_fmod(our_NAN, our_N_INF));
  ck_assert_double_nan(our_fmod(our_N_INF, our_NAN));
  ck_assert_double_nan(fmod(NAN, INFINITY));
  ck_assert_double_nan(fmod(INFINITY, NAN));
  ck_assert_double_nan(fmod(NAN, -INFINITY));
  ck_assert_double_nan(fmod(-INFINITY, NAN));
  ck_assert_ldouble_eq_tol(fmod(2.4, 0.5), our_fmod(2.4, 0.5), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(2.4, -0.5), our_fmod(2.4, -0.5), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(-2.4, 0.5), our_fmod(-2.4, 0.5), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(-2.4, -0.5), our_fmod(-2.4, -0.5), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(666666.4, 1.5), our_fmod(666666.4, 1.5), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(666666.4, -1.5), our_fmod(666666.4, -1.5),
                           1e-8);
  ck_assert_ldouble_eq_tol(fmod(3.3, 24.2), our_fmod(3.3, 24.2), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(3.3, -24.2), our_fmod(3.3, -24.2), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(-3.3, -24.2), our_fmod(-3.3, -24.2), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(0.0000000005543, 24.2),
                           our_fmod(0.0000000005543, 24.2), 1e-8);
  ck_assert_ldouble_eq_tol(fmod(0.0000000005543, 0.000003),
                           our_fmod(0.0000000005543, 0.000003), 1e-8);
}
END_TEST

START_TEST(test_fmod2) {
  for (double a = -1500; a < 1500; a += 123) {
    for (double b = -12; b < 12; b += 1.25) {
      ck_assert_double_eq(fmod(a, b), our_fmod(a, b));
      ck_assert_double_eq(fmod(b, a), our_fmod(b, a));
    }
  }
}
END_TEST

START_TEST(test_log1) {
  for (double k = 1; k < 100; k += 13.2) {
    double a = log(k);
    double b = our_log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_log2) {
  for (double k = 0.1; k < 4; k += 0.24) {
    double a = log(k);
    double b = our_log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_log3) {
  for (double k = 0.1; k < 10000; k += 123) {
    double a = log(k);
    double b = our_log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_log4) {
  for (double k = 0.000005; k < 1; k *= 5) {
    double a = log(k);
    double b = our_log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_log5) {
  ck_assert_ldouble_eq_tol(log(0.5), our_log(0.5), 1e-15);
  ck_assert_ldouble_nan(our_log(-0.5));
  ck_assert_ldouble_eq_tol(log(1), our_log(1), 1e-6);
  ck_assert_ldouble_eq_tol(log(1.1), our_log(1.1), 1e-6);
  ck_assert_ldouble_infinite(our_log(0));
  ck_assert_ldouble_infinite(our_log(-0));
  ck_assert_ldouble_eq_tol(log(5.123456789123), our_log(5.123456789123), 1e-15);
  ck_assert_ldouble_eq(log(INFINITY), our_log(our_P_INF));
  ck_assert_ldouble_nan(our_log(our_NAN));
  ck_assert_ldouble_nan(our_log(our_N_INF));
}
END_TEST

START_TEST(test_pow) {
  ck_assert_ldouble_eq_tol(pow(0, 2.4), our_pow(0, 2.4), 1e-8);
  ck_assert_ldouble_eq_tol(pow(-0, 2.4), our_pow(-0, 2.4), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, 0), our_pow(2.4, 0), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, -0), our_pow(2.4, -0), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, 0.5), our_pow(2.4, 0.5), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, -0.5), our_pow(2.4, -0.5), 1e-8);
  ck_assert_ldouble_nan(our_pow(-2.4, 0.5));
  ck_assert_ldouble_nan(our_pow(-2.4, -0.5));
  ck_assert_ldouble_nan(our_pow(-2.4, 2.1));
  ck_assert_ldouble_nan(our_pow(-2.4, -2.1));
  ck_assert_ldouble_eq_tol(pow(-2.4, 2), our_pow(-2.4, 2), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, 2), our_pow(2.4, 2), 1e-8);
  ck_assert_ldouble_eq_tol(pow(-2.4, -1), our_pow(-2.4, -1), 1e-8);
  ck_assert_ldouble_nan(our_pow(-2.4, -1.2));
  ck_assert_ldouble_nan(our_pow(-2.4, -0.4));
  ck_assert_ldouble_eq_tol(pow(2.4, 1), our_pow(2.4, 1), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, 3), our_pow(2.4, 3), 1e-8);
  ck_assert_ldouble_eq_tol(pow(2.4, -3), our_pow(2.4, -3), 1e-8);
  ck_assert_ldouble_eq_tol(pow(666666.4, -1.5), our_pow(666666.4, -1.5), 1e-5);
  ck_assert_ldouble_eq_tol(pow(3.3, 13.2), our_pow(3.3, 13.2), 1e-6);
  ck_assert_ldouble_eq_tol(pow(3.3, -24.2), our_pow(3.3, -24.2), 1e-8);
  ck_assert_ldouble_nan(our_pow(-3.3, -24.2));
}
END_TEST

START_TEST(test_sin) {
  ck_assert_ldouble_eq_tol(sin(0.5), our_sin(0.5), 1e-15);
  ck_assert_ldouble_eq_tol(sin(-0.5), our_sin(-0.5), 1e-15);
  ck_assert_ldouble_eq_tol(sin(-1), our_sin(-1), 1e-15);
  ck_assert_ldouble_eq_tol(sin(1), our_sin(1), 1e-15);
  ck_assert_ldouble_eq_tol(sin(1.1), our_sin(1.1), 1e-15);
  ck_assert_ldouble_eq_tol(sin(-2.1), our_sin(-2.1), 1e-15);
  ck_assert_ldouble_nan(our_sin(our_N_INF));
  ck_assert_ldouble_nan(our_sin(our_P_INF));
  ck_assert_ldouble_nan(our_sin(our_NAN));
  ck_assert_ldouble_eq_tol(sin(0), our_sin(0), 1e-15);
  ck_assert_ldouble_eq_tol(sin(-0), our_sin(-0), 1e-15);
  ck_assert_ldouble_eq_tol(sin(5.123456789123), our_sin(5.123456789123), 1e-15);
  ck_assert_ldouble_eq_tol(sin(0.00000004564897), our_sin(0.00000004564897),
                           1e-15);
}
END_TEST

START_TEST(test_sqrt1) {
  for (double k = 0; k < 21; k += 3) {
    double a = sqrt(k);
    double b = our_sqrt(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
  }
}
END_TEST

START_TEST(test_sqrt2) {
  ck_assert_double_nan(our_sqrt(our_NAN));
  ck_assert_double_nan(sqrt(NAN));
  ck_assert_double_eq(our_sqrt(our_P_INF), sqrt(INFINITY));
  ck_assert_double_nan(our_sqrt(our_N_INF));
  ck_assert_double_nan(our_sqrt(-5));
  ck_assert_double_nan(sqrt(-5));
  ck_assert_double_eq_tol(sqrt(1000), our_sqrt(1000), 1e-7);
  ck_assert_ldouble_eq_tol(sqrt(0.5), our_sqrt(0.5), 1e-15);
  ck_assert_ldouble_nan(our_sqrt(-0.5));
  ck_assert_ldouble_eq_tol(sqrt(1), our_sqrt(1), 1e-15);
  ck_assert_ldouble_eq_tol(sqrt(1.1), our_sqrt(1.1), 1e-15);
  ck_assert_ldouble_eq_tol(sqrt(0), our_sqrt(0), 1e-15);
  ck_assert_ldouble_eq_tol(sqrt(-0), our_sqrt(-0), 1e-15);
}
END_TEST

START_TEST(test_tan) {
  ck_assert_ldouble_eq_tol(tan(0.5), our_tan(0.5), 1e-15);
  ck_assert_ldouble_eq_tol(tan(-0.5), our_tan(-0.5), 1e-15);
  ck_assert_ldouble_eq_tol(tan(-1), our_tan(-1), 1e-15);
  ck_assert_ldouble_eq_tol(tan(1), our_tan(1), 1e-15);
  ck_assert_ldouble_eq_tol(tan(1.1), our_tan(1.1), 1e-15);
  ck_assert_ldouble_eq_tol(tan(-2.1), our_tan(-2.1), 1e-8);
  ck_assert_ldouble_eq_tol(tan(0), our_tan(0), 1e-15);
  ck_assert_ldouble_eq_tol(tan(-0), our_tan(-0), 1e-15);
  ck_assert_ldouble_eq_tol(tan(5.123456789123), our_tan(5.123456789123), 1e-14);
  ck_assert_ldouble_eq_tol(tan(0.00000004564897), our_tan(0.00000004564897),
                           1e-15);
  ck_assert_ldouble_eq_tol(tan(170000000.1), our_tan(170000000.1), 1e-7);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_abs);
  tcase_add_test(tc1_1, test_acos1);
  tcase_add_test(tc1_1, test_acos2);
  tcase_add_test(tc1_1, test_acos3);
  tcase_add_test(tc1_1, test_asin1);
  tcase_add_test(tc1_1, test_asin2);
  tcase_add_test(tc1_1, test_asin3);
  tcase_add_test(tc1_1, test_atan1);
  tcase_add_test(tc1_1, test_atan2);
  tcase_add_test(tc1_1, test_ceil);
  tcase_add_test(tc1_1, test_cos);
  tcase_add_test(tc1_1, test_exp1);
  tcase_add_test(tc1_1, test_exp2);
  tcase_add_test(tc1_1, test_exp3);
  tcase_add_test(tc1_1, test_exp4);
  tcase_add_test(tc1_1, test_fabs);
  tcase_add_test(tc1_1, test_floor);
  tcase_add_test(tc1_1, test_fmod1);
  tcase_add_test(tc1_1, test_fmod2);
  tcase_add_test(tc1_1, test_log1);
  tcase_add_test(tc1_1, test_log2);
  tcase_add_test(tc1_1, test_log3);
  tcase_add_test(tc1_1, test_log4);
  tcase_add_test(tc1_1, test_log5);
  tcase_add_test(tc1_1, test_pow);
  tcase_add_test(tc1_1, test_sin);
  tcase_add_test(tc1_1, test_sqrt1);
  tcase_add_test(tc1_1, test_sqrt2);
  tcase_add_test(tc1_1, test_tan);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
